"""empty message

Revision ID: 6cd208924c2e
Revises: d3e9a74521bf
Create Date: 2024-07-24 21:24:44.267247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cd208924c2e'
down_revision = 'd3e9a74521bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('mass',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('populate',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('diameter',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('gravity',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('orbital_period',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('surface_water',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('surface_water',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('orbital_period',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('gravity',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('diameter',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('populate',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('mass',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    # ### end Alembic commands ###
