"""empty message

Revision ID: 8c85e646505a
Revises: f3d985252841
Create Date: 2024-07-24 20:59:39.321857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c85e646505a'
down_revision = 'f3d985252841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_year', sa.String(length=250), nullable=True))
        batch_op.alter_column('height',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('mass',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('hair_color',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('eye_color',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('skin_color',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.drop_column('birth_yearr')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_yearr', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('skin_color',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('eye_color',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('hair_color',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('mass',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.drop_column('birth_year')

    # ### end Alembic commands ###
